spring:
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

retryMaxAttempt: ${RETRY_MAX_ATTEMPT:5}
retryInterval: ${RETRY_INTERVAL:2000}
cronTimer:
  reprocess: ${CRON_REPROCESS:0 */1 * * * *}
externalUrl: ${EXTERNAL_URL:https://api.postmon.com.br}
